server:
  port: 9100
spring:
  application:
    name: itcast-health-mobile
  redis:
    host: localhost
    port: 6379
dubbo:
  application:
    name: itcast-health-mobile
  registry:
    address: zookeeper://192.168.200.130:2181
    client: zkclient
    timeout: 60000
  consumer:
    timeout: 60000
  scan:
    base-packages: cn.itcast
wx:
  pay:
    notify_url: http://dwxw.vip.aeert.com/pay/notify
